# Generated by Django 2.2.5 on 2019-09-08 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CuratedPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('song_title', models.CharField(max_length=200)),
                ('track_number', models.IntegerField(null=True)),
                ('deluxe_only', models.CharField(max_length=1)),
                ('single', models.CharField(max_length=1)),
                ('genre', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('bpm', models.IntegerField(default=0)),
                ('camelot', models.CharField(max_length=3)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlists.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongToSetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Song')),
                ('tour_setlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Album')),
            ],
        ),
        migrations.CreateModel(
            name='SongToCuratedPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.CuratedPlaylist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.Song')),
            ],
        ),
    ]
